name: Trigger auto deployment for lesearch-frontend-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/lesearch-frontend-app-AutoDeployTrigger-73bdfb86-f581-45bf-8d5c-e070e6b2c262.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.LESEARCHFRONTENDAPP_AZURE_CREDENTIALS }}
          
      # Step to create .env.local file
      - name: Create .env.local file
        run: |
          echo "NEXT_PUBLIC_APP_URL=${{ vars.NEXT_PUBLIC_APP_URL }}" >> .env.local
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env.local
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env.local
          echo "NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY }}" >> .env.local
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env.local
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env.local
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env.local
          cat .env.local
          
      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: lesearchallregistry.azurecr.io
          registryUsername: ${{ secrets.LESEARCHFRONTENDAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LESEARCHFRONTENDAPP_REGISTRY_PASSWORD }}
          containerAppName: lesearch-frontend-app
          resourceGroup: LeSearch
          imageToBuild: lesearchallregistry.azurecr.io/lesearch-frontend-image:${{ github.sha }}
          
            

     

